#!/bin/sh -e

# build
#	Simple PiLCDMenuController build and install script
#
#	Copyright (c) 2017-2018 Albert Nadal Garriga
#################################################################################
# This file is part of PiLCDMenuController:
#	A controllable text menu to run with a standard 16x2 LCD and a Joystick on
#	Raspberry Pi devices
#
#    PiLCDMenuController is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    PiLCDMenuController is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with PiLCDMenuController.  If not, see <http://www.gnu.org/licenses/>.
#################################################################################

check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then please email all the output and as many details as you can to"
    echo "  anadalg@gmail.com"
    echo ""
    exit 1
  fi
}

sudo=${WIRINGPI_SUDO-sudo}

if [ x$1 = "xclean" ]; then
  echo -n "PiLCDMenuController:   "        ; make clean
  cd third_parties/wiringPi/wiringPi
  echo -n "wiringPi:   "	; make clean
  cd ../devLib
  echo -n "DevLib:     "	; make clean
  cd ../gpio
  echo -n "gpio:       "	; make clean
  cd ../examples
  echo -n "Examples:   "	; make clean
  cd Gertboard
  echo -n "Gertboard:  "	; make clean
  cd ../PiFace
  echo -n "PiFace:     "	; make clean
  cd ../q2w
  echo -n "Quick2Wire: "	; make clean
  cd ../PiGlow
  echo -n "PiGlow:     "	; make clean
  cd ../scrollPhat
  echo -n "scrollPhat: "	; make clean
  exit
fi

if [ x$1 = "xuninstall" ]; then
  echo -n "PiLCDMenuController: " ; $sudo make uninstall
  exit
fi

if [ x$1 != "x" ]; then
  echo "Usage: $0 [clean | uninstall]"
  exit 1
fi

  echo "PiLCDMenuController Build script"
  echo "================================"
  echo

  hardware=`fgrep Hardware /proc/cpuinfo | head -1 | awk '{ print $3 }'`

#  if [ x$hardware != "xBCM2708" ]; then
#    echo ""
#    echo "   +-----------------------------------------------------------------------+"
#    echo "   |   PiLCDMenuController is designed to run on the Raspberry Pi only.    |"
#    echo "   |         This processor does not appear to be a Raspberry Pi.          |"
#    echo "   +-----------------------------------------------------------------------+"
#    echo ""
#    exit 1
#  fi

  echo
  echo "WiringPi Library"
  cd third_parties/wiringPi/wiringPi
  $sudo make clean
  make -j5 static
  check_make_ok
  make -j5
  check_make_ok
  $sudo make copy-files
  check_make_ok

  echo
  echo "WiringPi Devices Library"
  cd ../devLib
  $sudo make clean
  make -j5 static
  check_make_ok
  make -j5
  check_make_ok
  $sudo make copy-files
  check_make_ok

  echo
  echo "PiLCDMenuController Library"
  cd ../../../
  $sudo make clean
  $sudo make uninstall
  make
  check_make_ok
  make static
  check_make_ok
  $sudo make copy-files
  check_make_ok
  make lcdmenu
  #  $sudo make install

# echo
# echo "Examples"
# cd ../examples
# make
# cd ..

echo
echo All Done.
echo ""
echo "NOTE: To compile programs with PiLCDMenuController, you need to add:"
echo "    -lpiLCDMenuController"
echo "  to your compile line(s)."
echo ""
